// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBRtiz3Ok6rkr42GT7JbTubfWaGCTN-k',
    appId: '1:604740015759:web:09621a3c8f753789f7c2fa',
    messagingSenderId: '604740015759',
    projectId: 'ht-hn-bd98b',
    authDomain: 'ht-hn-bd98b.firebaseapp.com',
    databaseURL: 'https://ht-hn-bd98b-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'ht-hn-bd98b.firebasestorage.app',
    measurementId: 'G-KV639BZQT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCub6wm8m0eugKw0yVYTova8S_ciblsHC4',
    appId: '1:604740015759:android:07c1433c1bdb6a83f7c2fa',
    messagingSenderId: '604740015759',
    projectId: 'ht-hn-bd98b',
    databaseURL: 'https://ht-hn-bd98b-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'ht-hn-bd98b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxMXwGkQUf3XZzaAcsoZKyE1wRTT6piw',
    appId: '1:604740015759:ios:bc3ce7cbbe6bf681f7c2fa',
    messagingSenderId: '604740015759',
    projectId: 'ht-hn-bd98b',
    databaseURL: 'https://ht-hn-bd98b-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'ht-hn-bd98b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxMXwGkQUf3XZzaAcsoZKyE1wRTT6piw',
    appId: '1:604740015759:ios:bc3ce7cbbe6bf681f7c2fa',
    messagingSenderId: '604740015759',
    projectId: 'ht-hn-bd98b',
    databaseURL: 'https://ht-hn-bd98b-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'ht-hn-bd98b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBRtiz3Ok6rkr42GT7JbTubfWaGCTN-k',
    appId: '1:604740015759:web:62a2faeddedd6d49f7c2fa',
    messagingSenderId: '604740015759',
    projectId: 'ht-hn-bd98b',
    authDomain: 'ht-hn-bd98b.firebaseapp.com',
    databaseURL: 'https://ht-hn-bd98b-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'ht-hn-bd98b.firebasestorage.app',
    measurementId: 'G-6FBZ4X5SZY',
  );
}
